version: '3'

services:
  pgsql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
    networks:
      - prod-network

  standardis4:
    image: standardis4
    build:
      context: ./StandardIS4
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      ConnectionString: "Host=pgsql;Userid=syslabuser;Password=verycomplicatedpwd;Database=LabApiDb;Port=5432;Pooling=true"
      ASPNETCORE_ENVIRONMENT: Development
    links:
      - pgsql
    depends_on:
      - pgsql
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge